[package]
name = "superlight-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
superlight-common = { path = "../common" }
base64 = "0.22"
flate2 = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "process", "sync", "io-util", "io-std", "time"] }
serde_json = "1"
portable-pty = "0.8"
notify = "8.2.0"
